---
title: "NixNA"
format:
  revealjs: 
    theme: solarized
---

# NixNa (*Remove your NA's in one second)*

Why NixNa

-   Dealing with missing data is an important step in data cleaning

-   With a large data set we might need to remove rows with NA's, but our approaches may vary according to the goal of the analyis

-   This will clean our data and prepare us for the next steps 


## Install the Package


install the development version from GitHub

devtools::install_github("sarraalii/NixNa")

library(NixNa)

# Function 1

trimun: Remove Rows for Unique Values with Missing Covariates

## Example trimun()

-   Testing the trimun function to remove all countries if atleast one of them has a missing value in a define covariate colum

-   Specify the column and covariates unique_column \<- "country_name" covariates \<- c("GDP", "popdens", "urban", "male_edu" Call the function cleaned_data \<- trimun(conflictdata, unique_column, covariates)

This will remove rows from all unique countries if it had any missing in the defined covariates


# Function 2

trimcovNa: Remove rows with missing values in specified covariate column

## Example trimcovNa()

-   Test by defining the target column and covariate columns

-   target_column \<- "country_name"

-   covariate_columns \<- c("GDP", "male_edu", "temp")

-   Use the redefined function to clean the conflictdata dataset

-   cleaned_covariates \<- trimcovNa(conlifctdata, target_col = target_column, covariate_cols = covariate_columns)

## Data Description

conflict data loads with the package

|                                                                                                                                                                                                                                     |
|------------------------------------------------------------------------|
| Data to demonstrate the trimun and trimcovNa function Description: Data for 181 countries from the Uppsala Conflict Data Program and World Bank for the years 2000 to 2019. The dataset includes various socio-economic indicators. |

## Conclusion

-   Data cleanliness is essential for accurate and reliable results in data analysis.

-   Care should be taken to choose appropriate methods for handling missing data based on the nature of the dataset and the analysis goals.

-   The process of handling missing data is a key preprocessing step that contributes to the overall data quality and integrity.

-   A well-cleaned dataset sets the foundation for effective and meaningful insights during the data analysis pipeline.

## Resources

-   [Official Documentation](link-to-documentation)

-   [Github Respository](https://github.com/Sarraalii/NixNa.git)

-   [Data Source](https://pubmed.ncbi.nlm.nih.gov/34582455/)

    # Thank you
